### PR TITLE
remove `es5` fallback

### PR DESCRIPTION
**Pull request by bekzod**
maybe I am stepping ahead of myself here, but since most of ember core libs already dropped `es5` fallbacks, I think `rsvp` should also drop them going 4.0, free to close if you have other thoughts

### CODE REVIEW

**Comment by stefanpenner** [comment]
seems good, we will need to likely do a major version bump when releasing though.

**Comment by stefanpenner** [comment]
i would like to release this as 4.0 we can make 5.0 the bigger release. Thoughts?

**Comment by bekzod** [comment]
awesome agreed!

**Comment by stefanpenner** [comment]
@bekzod can you think of anything blocking me from releasing 4.0 today? I can't think of anything.

**Comment by bekzod** [comment]
Will it be just es5 fallback drop? then nope its all green to release

**Comment by stefanpenner** [comment]
needs a rebase post: https://github.com/tildeio/rsvp.js/pull/456

**Comment by stefanpenner** [comment]
then we can cut 4.0 with this and the eager stuf

**Comment by bekzod** [comment]
Can do only after one hour

**Comment by stefanpenner** [comment]
released as v4.0.0 🎉

**Pull request merged**
