### PR TITLE
Upgrades

### PR DESCRIPTION
**Pull request by stefanpenner**
- less bytes
- faster builds
- more ES6
- rollup over es6modules stuff

- [x] https://github.com/eploko/broccoli-watchify/pull/2

### CODE REVIEW

**Comment by krisselden** [comment]
@stefanpenner can I merge this if I fix the Travis build?

**Comment by krisselden** [comment]
I got rid of the Promise undefined issue for rollup but the broccoli-watchify stuff mistifies me

**Comment by krisselden** [comment]
@stefanpenner did you forget to push something to stefanpenner/broccoli-watchify#fixes ? also, can you just release your fixes? the base project hasn't been updated in 2 years.

**Comment by stefanpenner** [comment]
@krisselden once im back from vacation, i'll likely release a fork for broccoli-watchify.

**Comment by stefanpenner** [comment]
@krisselden  https://twitter.com/eploko/status/771016999509950464

**Comment by stefanpenner** [comment]
> @stefanpenner did you forget to push something to stefanpenner/broccoli-watchify#fixes ? also, can you just release your fixes? the base project hasn't been updated in 2 years.

Just double checked, the ones that are pushed seem to work fine. e.g. (tests pass) Could you share what the issue is for you?

**Comment by stefanpenner** [comment]
@krisselden just got commit + release for broccoli-watchify. I still need to write tests for that PR before i can release... maybe i'll be able to sneak some  more computering in during vacation without getting in trouble :P

**Pull request merged**
