### PR TITLE
improve filter method

### PR DESCRIPTION
**Pull request by AmilKey**
Improving the filter method for promise which returns an array

### CODE REVIEW

**Comment by stefanpenner** [comment]
This should likely not branch. As a promise input may still fulfill to an array of promises that need to be all'd

**Comment by AmilKey** [comment]
@stefanpenner do you mean?
Promise.resolve(promise, label).then(res=> Promise.all(res))

**Comment by stefanpenner** [comment]
@amiel ya i believe so

**Comment by AmilKey** [comment]
@stefanpenner updated

**Pull request merged**
