### PR TITLE
new namespace

### PR DESCRIPTION
**Pull request by bekzod**
moving helpers to new namespace as described #261

### CODE REVIEW

**Comment by bekzod** [comment]
this is what is left after namespace movement```export {
  asap,
  Promise,
  EventTarget,
  configure,
  on,
  off,
  async
};```  or everything should be moved to `Promise` namespace

**Comment by stefanpenner** [comment]
> or everything should be moved to Promise namespace ?

no that looks correct

**Comment by stefanpenner** [comment]
But whats the plan for ember? We likely need a compat shim or something?

**Comment by bekzod** [comment]
don't have much experience with compatibility/shims, if you lead/guide me I can do whatever you have in mind

**Comment by stefanpenner** [comment]
@bekzod sounds good. I'll take time later this week to put together some thoughts :)

**Comment by bekzod** [comment]
@stefanpenner ping should I update this PR ? what would be the plan to do depreciation and aliasing in ember core level and just drop old namespace in RSVP level?

**Comment by stefanpenner** [comment]
I personally prefer this, but I worry re: churn.

@rwjblue would love your thoughts on this as well.

**Comment by wagenet** [comment]
Closing due to staleness.

**Pull request closed without merging**
