### PR TITLE
first iteration on adding an API docs site

### PR DESCRIPTION
**Pull request by mikepmunroe**
start of fix for issue #235 

for now, the site is manually generated using grunt docs task and uses
default YUIdoc styles

future iteration should be similar to jekyll site used for EAK - see
https://github.com/stefanpenner/ember-app-kit/tree/gh-pages

future iterations should also include styles that match other Ember
sites

### CODE REVIEW

**Comment by williamsbdev** [comment]
I have the domain rsvpjs.com and would love to get it transferred if someone else would like to take it over. Otherwise right now it is setup for gh-pages. Just add the CNAME file with rsvpjs.com. Thanks!

**Comment by stefanpenner** [comment]
@williamsbdev sorry, i keep meaning to give you the info to transfer it. What would be easiest?

**Comment by williamsbdev** [comment]
No worries! I've honestly never transferred a domain before so I'm assuming I just need to know where to transfer it. I'll work with Hover to get that done.

**Comment by stefanpenner** [comment]
https://rsvpjs.com now points to this repo's GH pages. thanks to @williamsbdev   

one step closer

**Comment by ksnyde** [comment]
what ever happened to this? The https://rsvpjs.com URL seems to be down. I had a question about `race` which I was able to figure by myself but it appeared that this documentation might have answered this. :)

**Comment by williamsbdev** [comment]
There is no SSL. it is simply http://rsvpjs.com. Since there is no index.html, GH pages does not have anything to supply for this domain. If we were to submit a PR with an index.html, that would get this repo going.

**Comment by uitgewis** [comment]
I think this may have become less relevant since the API docs are also part of the Ember API docs: http://emberjs.com/api/classes/RSVP.html

But I think there's merit in getting proper docs up, as the Ember site doesn't cover most of the modules within `rsvp/*`. I had to delve into the source to get documentation recently.

**Comment by ksnyde** [comment]
I would think the primary function of having docs on the `rsvpjs.com` site is to help nodejs users rather than Ember developers. Regardless, a single source seems a good idea and maybe we could:

- abandon the separate RSVP website
- update the README to point to Ember's docs
- update Ember docs to give full RSVP coverage
- _possibly_ also have a section that just mentions nodejs/backend use cases

**Comment by williamsbdev** [comment]
Just chiming in to see if people would like me to renew the domain. I got an email about the automatic renewal in a couple months. If we think just adding to the Ember docs is a viable option, I will not renew the http://rsvpjs.com domain.

**Pull request closed without merging**
