### PR TITLE
[FEATURE] allow passing promise values to hash/map/hashSettled

### PR DESCRIPTION
**Pull request by bekzod**
just to align things with `RSVP.filter` which supports promise value

### CODE REVIEW

**Comment by bekzod** [comment]
@stefanpenner maybe this is good to merge :P

**Comment by bekzod** [comment]
@stefanpenner ping :)

**Comment by stefanpenner** [comment]
needs rebase, then i'll merge.

Thanks! Sorry for letting this linger

**Comment by bekzod** [comment]
no worries, done

**Comment by bekzod** [comment]
ping

**Pull request merged**
