### PR TITLE
reverted `enumerator` and `promise` to es5 class

### PR DESCRIPTION
**Pull request by bekzod**
ember seems unhappy with 3.6.0 release, https://github.com/emberjs/ember.js/pull/15441 
particularly when running 
`TEST_SUITE=built-tests EMBER_ENV=production DISABLE_JSCS=true DISABLE_JSHINT=true npm test`, this fixes it

### CODE REVIEW

**Comment by stefanpenner** [comment]
Any ideas what the issue was?

**Comment by bekzod** [comment]
nope :P didn't understand what is going on in tests there too many things :) spend a lot of time to find the solution, tried all previous commits one by one starting from 3.5.0 :P

**Comment by stefanpenner** [comment]
released as 4.6.1

**Comment by rwjblue** [comment]
Hmm. Seems like you meant to release as 3.6.1?

**Comment by stefanpenner** [comment]
Ug releasing before coffee is a bad idea.  I'm not near my machine @rwjblue got a minute to correct? Otherwise I can correct in about 30m

**Comment by rwjblue** [comment]
Sadly, I am not listed on `npm owner ls rsvp` so I can't do it 😭

**Comment by stefanpenner** [comment]
released as v3.6.1 🎉

**Comment by kellyselden** [comment]
Is it too late to unpublish 4.6.1? It is still showing up in the version list.

**Comment by stefanpenner** [comment]
@kellyselden NPM was hanging forever when I tried... (3 days ago)

**Pull request merged**
