### PR TITLE
Update -internal.js

### PR DESCRIPTION
**Pull request by hashplus**

### CODE REVIEW

**Comment by mixonic** [comment]
@hashplus can you provide some context or a test case? This is a bugfix?

**Comment by hashplus** [comment]
@mixonic , in ie7  throw `constructor` not defined error. so i find this   `constructor.resolve` in source code , in browser this equals to `window.constructor.resolve` ( ie<8 can't call `constructor` on `window` ).  in higher version ie works well because it always return undefined (it could be author's mistake). it should solve this [#271](https://github.com/tildeio/rsvp.js/issues/271).

-------------
sorry for my poor english

**Comment by stefanpenner** [comment]
this looks like a bug, but a test case is required before merging. (good find)

**Comment by stefanpenner** [comment]
@hashplus can you provide a test?

**Pull request closed without merging**
