### PR TITLE
Added browser field to fix browserification

### PR DESCRIPTION
**Pull request by ArtskydJ**
I was unable to browserify my code that relies on this module.

I added this field, and browserify worked fine...

### CODE REVIEW

**Comment by stefanpenner** [comment]
Will release soon.  Not at a computer currently

**Comment by ArtskydJ** [comment]
Related issues/pull requests: #339 #340 #352 #358

**Comment by ArtskydJ** [comment]
Any chance of publishing this to npm?

**Comment by stefanpenner** [comment]
@ArtskydJ I am away from my machine (just moved east coast -> west coast) but maybe @fivetanley can release?

**Comment by ArtskydJ** [comment]
Thanks for releasing it @fivetanley!

**Pull request merged**
