### PR TITLE
fix issue with `swallowing reject after finally`

### LINKED ISSUE #497: Finally swallows reject if rejected with no value
Given a promise with `finally` block, if we reject without a value then the promise resolves when I'd expect it to reject.

```javascript
new RSVP.Promise((resolve, reject) => { 
  reject() // reject with no value
}).finally(() => {
  console.log('finally called')
}).then(() => { 
  console.log('then called')
}).catch(e => { 
  console.log('reject called')
})

// => 
// finally called
// then called
```

Changing this to reject with a value works:

```javascript
new RSVP.Promise((resolve, reject) => { 
  reject(true) // reject with a value
}).finally(() => {
  console.log('finally called')
}).then(() => { 
  console.log('then called')
}).catch(e => { 
  console.log('reject called')
})

// => 
// finally called
// reject called
```

### PR DESCRIPTION
**Pull request by bekzod**
fixes #497 
was introduced here https://github.com/tildeio/rsvp.js/commit/2788fe9f6247ba9a4f3c04278f304d23dedb66ef

cc @stefanpenner @rwjblue

### CODE REVIEW

**Comment by stefanpenner** [comment]
ooo

**Comment by stefanpenner** [comment]
hmm, apparently I am not an owner of this repo anymore... @wycats  / @chancancode maybe some github admin housekeeping gone sideways? (it looks like i am sill an owner of router-recognizer and router.js)

**Comment by stefanpenner** [comment]
@bekzod  this may also be an issue with es6-promise, if you have cycles could you take a look?

I'll see if i can sort out the permissioning issue above so we can ship.

**Comment by stefanpenner** [comment]
released as v4.0.2 🎉

**Comment by rlivsey** [comment]
:+1: thank you @bekzod

**Pull request merged**
