### PR TITLE
Use `platform` instead of `window`

### PR DESCRIPTION
**Pull request by seanpdoyle**

### CODE REVIEW

**Comment by rwjblue** [comment]
:+1:

**Comment by stefanpenner** [comment]
I don't believe this is actually correct

**Comment by seanpdoyle** [comment]
@stefanpenner should the `*.umd.js` exclusion happen in each microlib, or should it happen in the Ember build?

**Comment by stefanpenner** [comment]
> @stefanpenner should the *.umd.js exclusion happen in each microlib, or should it happen in the Ember build?

ember-build likely.

**Comment by rwjblue** [comment]
Agreed, would be much easier to exclude in emberjs-build

**Pull request merged**
